### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by linsir123** [zeroiszero/containerized-laravel#1]
deployment.yaml

```
                    envFrom:
                        - 
                            configMapRef:
                                name: configmap-laravel-env
```

将配置信息传入为pod的环境变量，laravel中要如何读取到这些环境变量呢？
